version: "3.9"

services:
  web:
    image: promptopia:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
